// <auto-generated />
using System;
using GPE.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPE.Infrastructure.Migrations
{
    [DbContext(typeof(ContextApp))]
    [Migration("20250805195933_add_field_lastLogin")]
    partial class add_field_lastLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPE.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSeguroSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalarioSemanal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoEmpleado")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasDiscriminator<string>("TipoEmpleado").HasValue("Empleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GPE.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GPE.Domain.Entities.EmpleadoAsalariado", b =>
                {
                    b.HasBaseType("GPE.Domain.Entities.Empleado");

                    b.HasDiscriminator().HasValue("Asalariado");
                });

            modelBuilder.Entity("GPE.Domain.Entities.EmpleadoAsalariadoPorComision", b =>
                {
                    b.HasBaseType("GPE.Domain.Entities.Empleado");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("AsalariadoPorComision");
                });

            modelBuilder.Entity("GPE.Domain.Entities.EmpleadoPorComision", b =>
                {
                    b.HasBaseType("GPE.Domain.Entities.Empleado");

                    b.Property<decimal>("TarifaComision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VentasBrutas")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Empleados", t =>
                        {
                            t.Property("TarifaComision")
                                .HasColumnName("EmpleadoPorComision_TarifaComision");

                            t.Property("VentasBrutas")
                                .HasColumnName("EmpleadoPorComision_VentasBrutas");
                        });

                    b.HasDiscriminator().HasValue("PorComision");
                });

            modelBuilder.Entity("GPE.Domain.Entities.EmpleadoPorHoras", b =>
                {
                    b.HasBaseType("GPE.Domain.Entities.Empleado");

                    b.Property<decimal>("HorasTrabajadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoPorHora")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PorHoras");
                });
#pragma warning restore 612, 618
        }
    }
}
